# Generated by Django 5.1.3 on 2025-02-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='list',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
    ]
